version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: manga
    ports:
      - "27017:27017"
    volumes:
      - /home/thamires/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
  manga:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: manga
    environment:
      - SPRING_PROFILES_ACTIVE=test, docker
      - SPRING_DATA_MONGODB_URI=mongodb://root:manga@mongo:27017/manga?authSource=admin
    ports:
      - "8080:8080"
      - "8083:8083"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: manga
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: manga
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge